### ISSUE TITLE
Router links from main body should scroll to top of page

### ISSUE THREAD

**Issue by pgoldtho** [visulate/visulate-for-oracle#39]
Following a link in an object report e.g. FK or dependency should scroll to the top of the page.

**Comment by pgoldtho** [comment]
https://stackoverflow.com/questions/48048299/angular-5-scroll-to-top-on-every-route-click/48048822

**Comment by goldthorp** [comment]
Haven't had any luck fixing this so far. First I tried getting a reference to the div containing all the contents and setting scrollTop to 0 in DbContentComponent:processObject. But I found that the scrollTop on that element is actually always 0 no matter where I scroll.

Then I saw the `scrollPositionRestoration` solution in that^ SO issue, which definitely seems like the correct way to do it, but I found it made no difference.

**Comment by goldthorp** [comment]
Oh, I see. The div I was looking actually has the height of the full content, so that element itself doesn't actually scroll. It's the mat-sidenav-content I actually need to set scrollTop = 0 on

**Comment by goldthorp** [comment]
Still, I was expecting a more angular-ey solution to this (i.e. something like scrollPositionRestoration in the app-routing.module.ts). Will look more into that because I'm still not sure why it didn't work.

**Comment by pgoldtho** [comment]
Did you try this?

https://stackoverflow.com/questions/39601026/angular-2-scroll-to-top-on-route-change/51915623#51915623

**Comment by goldthorp** [comment]
That works, as long as I add a div around the <router-outlet>. It's led to some other styling issues that I'm working on though

**Comment by goldthorp** [comment]
I also noticed the z-index should be increased on the navbar because the show line numbers toggle button shows up on top of it

**Comment by pgoldtho** [comment]
We had something similar to the unwanted scrollbar issue you described yesterday on my last project.  Fixed it using css:
```
/* Set height of categories region to view height - (header + footer height) */
.categories {
    overflow-x:hidden;
    height: calc(100vh - 233px);
}
```
