### ISSUE TITLE
Security alert - serialize-javascript

### ISSUE THREAD

**Issue by goldthorp** [visulate/visulate-for-oracle#59]
https://github.com/visulate/visulate-for-oracle/network/alerts

**Comment by goldthorp** [comment]
From the "Impact" section of alert details:

> This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

If serialized data of regular expression objects are used in an environment other than Node.js, it is affected by this vulnerability.

**Comment by goldthorp** [comment]
The app is node, right? So does that mean this doesn't affect us?

Anyway, they're saying it will be addressed in angular 8.3, but in the meantime we could add 

 `"resolutions": {
    "serialize-javascript": "^2.1.1"
  }`

In our package.json to get the alert to go away. Not sure if that's necessary though

**Comment by pgoldtho** [comment]
Waiting for patch mentioned in https://github.com/angular/angular-cli/issues/16414

**Comment by pgoldtho** [comment]
fixed with angular update
